### ISSUE TITLE
spark-master: unrecognized service

### ISSUE THREAD

**Issue by evbo** [chali/hadoop-cdh-pseudo-docker#1]
it appears the dockerfile does not install spark-master or spark-worker. Is there a reason these aren't included? e.g.: sudo apt-get install spark-master spark-worker

**Comment by chali** [comment]
Hi evbo, yes there is a reason why they are not installed. This image has spark configured for running on top of YARN. It means there is no running service representing master and worker nodes. Spark cluster is constructed on demand with YARN containers. You can take a look here http://www.cloudera.com/content/www/en-us/documentation/enterprise/latest/topics/cdh_ig_running_spark_on_yarn.html for details. You can run bash within that container and then you can use examples from the linked page.

Use this `docker exec -it cdh /bin/bash` for bash execution within container.
